### ISSUE TITLE
How to contribute? 

### ISSUE THREAD

**Issue by PedroVinicius** [boleto-br/boleto-br#6]
Hey guys!

I need something like this for my project. But unfortunatelly, I didn't found a complete solution for bills generation with Node.js. My company works with Bradesco, Santander and Sicoob. 

Is this project being mantained? I'm willing to contribute.

**Comment by thiamsantos** [comment]
@PedroVinicius now you can read the [contributing guidelines](https://github.com/boleto-br/boleto-br/blob/master/CONTRIBUTING.md). If you have any questions, feel free to ask :wink:
