### ISSUE TITLE
Cálculo do fator de vencimento está errado (um dia a menos)

### ISSUE THREAD

**Issue by efc30** [boleto-br/boleto-br#7]
`expirationDay: new Date(2017, 11, 04)`
Resulta em 04/12/2017 como vencimento. 
Na linha digitável do Bradesco, o fator de vencimento apresentado é **7362**, quando deveria ser **7363**

Em **lib/utils/calculate-expiration-factor.js**, alterei a linha abaixo e resolveu para mim. Acredito que é pelo fato do dia 07/10/1997 também contar como um dia, ou seja, além da subtração é necessário soma mais um pelo dia inicial.
`var diff = Math.floor(((expirationTime - baseTime) / (24 * 3600 * 1000)) + 1);`

Desculpe não fazer um pull request, mas ainda estou estudando o git.

**Comment by RafaelC457ro** [comment]
Olá, acabei de gerar um teste com data que você colocou e gerou com data fator de vencimento está correto. Qual versão de node e sistema operacional você está usando? Segue abaixo o código usado e o arquivo gerado com boleto-pdf
```js
const fs = require('fs')
const { bill, bradesco } = require('boleto-br')
const bradescoPDF = require('boleto-pdf').bradesco

const bradescoBill = bill(bradesco)
const { generateBillData } = bradescoBill

const boletos = [
  {
    paymentPlace:
      'Pagável preferencialmente na rede Bradesco ou Bradesco Expresso.',
    beneficiary: 'UNICRED FLORIANÓPOLIS - CNPJ: 074.064.502/0001-12',
    beneficiaryAddress:
      'Rua Tenete Silveira, 315 - Centro - Florianópolis - SC  - CEP 88010-301',
    instructions:
      'Após o vencimento cobrar multa de 2,00% , mais juros ao mes de 1,00%.',
    agency: '7506',
    agencyDigit: '0',
    account: 54291,
    accountDigit: '1',
    expirationDay: new Date(2017, 11, 4),
    documentDate: new Date(2017, 7, 18),
    processingDate: new Date(2017, 7, 18),
    card: '09',
    documentNumber: '42493',
    ourNumber: '19000001208',
    value: 900,
    formatedValue: 'R$ 9,90',
    documentType: 'DS',
    accept: 'N',
    currencyType: 'Real (R$)',
    amount: ' ',
    valueOf: ' ',
    descountValue: ' ',
    otherDiscounts: ' ',
    feeValue: ' ',
    outherFees: ' ',
    chargeValue: ' ',
    payer: {
      name: 'Anita Albuquerque',
      registerNumber: '221.412.772-05',
      street: 'Rua Maria Gertrudes Coelho',
      number: '827',
      complement: ' ',
      district: 'Estrada Nova',
      city: 'Divinópolis',
      state: 'MG',
      postalCode: '35500-700'
    },
    guarantor: {
      name: 'ACME Telecomunicações Ltda',
      registerNumber: '074.064.502/0001-12',
      street: 'Servidão',
      number: '439',
      district: 'Estrada Nova',
      complement: ' ',
      city: 'Jaraguá do Sul',
      state: 'SC',
      postalCode: '89254-375'
    }
  }
]

generateBillData(boletos).then(data => {
  const promises = data.map(x => bradescoPDF(x))
  return Promise.all(promises)
}).then(pdfs => {
  pdfs.forEach((pdf, index) => {
    fs.writeFile('boleto' + index + '.pdf', pdf, 'binary', err => {
      if (err) {
        console.log('something bad happen')
      }

      console.log('file saved!')
    })
  })
}).catch(err => console.log(err))
```
[boleto0.pdf](https://github.com/boleto-br/boleto-br/files/1572705/boleto0.pdf)

**Comment by efc30** [comment]
Olá, eu copiei e colei o código acima num index.js e digitei `node index.js` para gerar o PDF, mas continuou colocando 7362, diferente do seu que é 7363 (coloquei abaixo o boleto gerado).

Resultado do meu node -v: v8.9.1
Resultado do meu npm -v: 5.6.0
Meu sistema operacional é Windows 7 32 bits

Para contribuir mais com o problema, segue abaixo o resultado dos comandos que executei no console do Chrome. Veja que a subtração dá 7362. Eu acredito que o fato de usar getTime pode resultar em comportamentos diferentes dependendo do horário que seja executado (eu estou executando às 11h da manhã), por isso que o seu deu certo. Eu fiz o mesmo teste de console abaixo, no mesmo horário, numa máquina com windows 10 64 bits e o resultado foi o mesmo.

```
> const expirationTime = new Date(2017, 11, 4).getTime()
undefined
> const baseTime = new Date(1997, 9, 7).getTime()
undefined
> Math.floor((expirationTime - baseTime) / (24 * 3600 * 1000))
7362
> new Date(2017, 11, 4).getTime()
1512352800000
> new Date(1997, 9, 7).getTime()
876193200000
> (new Date(2017, 11, 4).getTime() - new Date(1997, 9, 7).getTime())
636159600000
> 636159600000 / (24 * 3600 * 1000)
7362.958333333333
```

Ao invés de usar Math.floor, poderia usar o Math.ceil e daria certo, mas não sei se para todos os casos. Teria que dar uma estudada melhor. Estou sem tempo agora, mas vou olhar isso com calma.

[boleto0.pdf](https://github.com/boleto-br/boleto-br/files/1575509/boleto0.pdf)

**Comment by RafaelC457ro** [comment]
Você pode testa esse link no browser mesmo https://jsbin.com/borohagege/edit?html,js,console

**Comment by efc30** [comment]
Funcionou perfeito. Eu ia te sugerir o uso do moment.js, só não sabia se você se importaria de teu projeto ter essa dependência.

**Comment by RafaelC457ro** [comment]
Ajustei o projeto nesse commit fd499bd, basta atualizar  para a versão v0.1.2, já estará corrigido.
