### ISSUE TITLE
CNAB para registro de boleto com restrição após o vencimento.

### ISSUE THREAD

**Issue by jansilva** [boleto-br/boleto-br#8]
Olá Rafael, tudo bem? Uma pequena dúvida acerca da geração do CNAB de remessa. Se eu quiser registrar um boleto que não permita o pagamento após o vencimento, instrução 09(na página 21 do manual do Bradesco), é possível hoje usando a sua função de geração?

![nao_receber](https://user-images.githubusercontent.com/641565/39939840-e5e6e25c-552d-11e8-8142-e1253e74fbed.png)

**Comment by RafaelC457ro** [comment]
Olá @jansilva poderia enviar a documentação por e-mail ou por aqui mesmo, para eu dar uma olhada.

**Comment by jansilva** [comment]
Oi Rafael,

    Segue a doc solicitada.


Abs


--------------
*Linkedin*: Jan Palach Profile
<http://www.linkedin.com/pub/jan-palach/16/b1a/7a3>

2018-05-14 11:18 GMT-03:00 Rafael Castro <notifications@github.com>:

**Comment by jansilva** [comment]
[4008-524-0121-layout-cobranca-versao-portugues.pdf](https://github.com/boleto-br/boleto-br/files/2001310/4008-524-0121-layout-cobranca-versao-portugues.pdf)

**Comment by RafaelC457ro** [comment]
@jansilva acabei de subir uma versão v0.2.0 com adição de mais dois parâmetros, **instructionOne** e **instructionTwo** neles você pode colocar a configuração que você precisa. você pode olhar como usar 
usando a instrução que coloquei na documentação do bradesco  #10
