### ISSUE TITLE
Alinhamento no campo de informação dos beneficiários.

### ISSUE THREAD

**Issue by jansilva** [boleto-br/boleto-br#9]
Olá, tudo bom?

   Encontrei uma outra issue de alinhamento para o campo de beneficiário. Em ambas as fichas.

![alinhamento_endereco_beneficiario](https://user-images.githubusercontent.com/641565/39940274-1b440956-552f-11e8-8182-15601a03f815.png)

Att,

**Comment by RafaelC457ro** [comment]
Olá @jansilva isso é um problema com o boleto-pdf poderia abrir essa issue lá? Que damos uma olhada.

**Comment by jansilva** [comment]
Ah sim, desculpe eu postei na aba errada.
